### ISSUE TITLE
more info and some typos

### ISSUE THREAD

**Issue by luisdaniel** [lifewinning/seeingnetworks#1]
Hello!
This is super neat! Found this through the ITP alumni list. 
If you plan on adding more information, I recommend this reading: 
http://cromwell-intl.com/travel/usa/new-york-internet/
Not sure where he gets his info, but it's pretty interesting. 

Also, I found a couple of typos:
Level 3 Comms: 'NASDAQ'
111 Eighth Avenue: $2 billion, instead of million. 
Very last link to Private Circulation is bad.
Could also send you a pull request if you want

**Comment by lifewinning** [comment]
Hey!

Yeah, I've seen that website. It's great! It's a different website with a different intent. Like there's tons of useful leads in there, but most of the content is supposed to be from actual field experience or research that has more than one source. If that guy submitted a pull request, great, but I'd rather not just straight plagiarize it.

There is more content that I haven't put up yet, mostly because I'm still editing it and because I have like, a life and commitments and stuff. Sorry.  

Thanks for the note on the typos!
